import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "@/css/globals.css";

const notoSans = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.className} bg-black text-slate-50 max-w-dvw overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
